# ========================== VARIABLES ==========================
x-api-args: &api-args
  NAME: api
  DOCKER_NODE_VERSION: 18.17.0-slim
  DOCKER_UBUNTU_VERSION: jammy-20230624

x-frontend-args: &frontend-args
  NAME: frontend
  DOCKER_NODE_VERSION: 18.17.0-slim
  DOCKER_UBUNTU_VERSION: jammy-20230624


services:
# ========================== PRODUCTION ==========================
  api-prod:
    build:
      dockerfile: ./docker/Dockerfile.backend
      target: production
      args: *api-args

  frontend-prod:
    build:
      dockerfile: ./docker/Dockerfile.web
      target: production
      args: *frontend-args


# ========================== DEVELOPMENT ==========================
  api-dev:
    build:
      dockerfile: ./docker/Dockerfile.backend
      target: development
      args: *api-args
    env_file:
      - ./apps/api/.env
    environment:
      DATABASE_HOST: mysql-resource
      DATABASE_PORT: 3306
      DATABASE_USER: root
      DATABASE_PASSWORD: dev
      DATABASE_NAME: GeekCollectorsNetwork
    ports:
      - ${API_PORT:-3000}:${API_PORT:-3000}
    restart: unless-stopped
    volumes:
      - ./apps/api:/app/api:ro
    depends_on:
      mysql-resource:
        condition: service_healthy

  frontend-dev:
    build:
      dockerfile: ./docker/Dockerfile.web
      target: development
      args: *frontend-args
    env_file:
      - ./apps/frontend/.env
    environment:
      PORT: ${FE_PORT:-80}
    ports:
      - ${FE_PORT:-80}:${FE_PORT:-80}
    restart: unless-stopped
    volumes:
      - ./apps/frontend:/app/frontend:ro

  mysql-resource:
    image: mysql:8.3.0
    environment:
      MYSQL_ROOT_PASSWORD: dev
    volumes:
      # This volume is pretty redundant, but if the database crashed
      # during dev, it'll be nice not to lose the data you were working
      # with.
      - mysql-resource-ephemeral:/var/lib/mysql
      - ./docker/mysql/initdb:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
      interval: 5s
      timeout: 3s
      retries: 5

  phpmyadmin-resource:
    image: phpmyadmin:5.2.1
    environment:
      PMA_USER: root
      PMA_PASSWORD: dev
    links:
      - mysql-resource:db
    ports:
      - 3307:80
    depends_on:
      mysql-resource:
        condition: service_healthy

volumes:
  mysql-resource-ephemeral: {}

# ========================== TEMPLATES ==========================
# A list of templates for apps and packages
# x-example-app-args: &example-app-args
#   NAME: example-app
#   DOCKER_NODE_VERSION: 18.17.0-slim
#   DOCKER_UBUNTU_VERSION: jammy-20230624

# _app-dev:
#   build:
#     dockerfile: ./docker/Dockerfile.backend
#     target: development
#     args: *_app-args
#   restart: unless-stopped
#   volumes:
#     - ./apps/_app:/app/_app:ro
#   depends_on:
#     - _package-dev

# _package-dev:
#   build:
#     dockerfile: ./docker/Dockerfile.package
#     target: builder
#     args: *_package-args
#   restart: unless-stopped
#   volumes:
#     - ./packages/_package:/packages/_package:ro
